//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.01.17 at 10:33:15 PM CET
//


package zis.rs.zis.domain;

import zis.rs.zis.domain.documents.*;
import zis.rs.zis.domain.documents.collections.*;
import zis.rs.zis.domain.entities.*;
import zis.rs.zis.domain.entities.collections.*;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.example.myschema package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.myschema
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IzborPromenaLekara }
     *
     */
    public IzborPromenaLekara createIzborPromenaLekara() {
        return new IzborPromenaLekara();
    }

    /**
     * Create an instance of {@link IzvestajLekara }
     *
     */
    public IzvestajLekara createIzvestajLekara() {
        return new IzvestajLekara();
    }

    /**
     * Create an instance of {@link Lekar }
     *
     */
    public Lekar createLekar() {
        return new Lekar();
    }

    /**
     * Create an instance of {@link LekarskiRecept }
     *
     */
    public LekarskiRecept createLekarskiRecept() {
        return new LekarskiRecept();
    }

    /**
     * Create an instance of {@link MedicinskaSestra }
     *
     */
    public MedicinskaSestra createMedicinskaSestra() {
        return new MedicinskaSestra();
    }

    /**
     * Create an instance of {@link Pacijent }
     *
     */
    public Pacijent createPacijent() {
        return new Pacijent();
    }

    /**
     * Create an instance of {@link Pregled }
     *
     */
    public Pregled createPregled() {
        return new Pregled();
    }

    /**
     * Create an instance of {@link UputZaLaboratoriju }
     *
     */
    public UputZaLaboratoriju createUputZaLaboratoriju() {
        return new UputZaLaboratoriju();
    }

    /**
     * Create an instance of {@link UputZaSpecialistickiPregled }
     *
     */
    public UputZaSpecialistickiPregled createUputZaSpecialistickiPregled() {
        return new UputZaSpecialistickiPregled();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton }
     *
     */
    public ZdravstveniKarton createZdravstveniKarton() {
        return new ZdravstveniKarton();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.IzmenePromeneLekara }
     *
     */
    public ZdravstveniKarton.IzmenePromeneLekara createZdravstveniKartonIzmenePromeneLekara() {
        return new ZdravstveniKarton.IzmenePromeneLekara();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.IzvestajiLekara }
     *
     */
    public ZdravstveniKarton.IzvestajiLekara createZdravstveniKartonIzvestajiLekara() {
        return new ZdravstveniKarton.IzvestajiLekara();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.LekarskiRecepti }
     *
     */
    public ZdravstveniKarton.LekarskiRecepti createZdravstveniKartonLekarskiRecepti() {
        return new ZdravstveniKarton.LekarskiRecepti();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.UputiZaSpecialistickiPregled }
     *
     */
    public ZdravstveniKarton.UputiZaSpecialistickiPregled createZdravstveniKartonUputiZaSpecialistickiPregled() {
        return new ZdravstveniKarton.UputiZaSpecialistickiPregled();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.UputiZaLaboratoriju }
     *
     */
    public ZdravstveniKarton.UputiZaLaboratoriju createZdravstveniKartonUputiZaLaboratoriju() {
        return new ZdravstveniKarton.UputiZaLaboratoriju();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.Adresa }
     *
     */
    public ZdravstveniKarton.Adresa createZdravstveniKartonAdresa() {
        return new ZdravstveniKarton.Adresa();
    }

    /**
     * Create an instance of {@link UputZaSpecialistickiPregled.IzvestajSpecialiste }
     *
     */
    public UputZaSpecialistickiPregled.IzvestajSpecialiste createUputZaSpecialistickiPregledIzvestajSpecialiste() {
        return new UputZaSpecialistickiPregled.IzvestajSpecialiste();
    }

    /**
     * Create an instance of {@link UputZaSpecialistickiPregled.Pregled }
     *
     */
    public UputZaSpecialistickiPregled.Pregled createUputZaSpecialistickiPregledPregled() {
        return new UputZaSpecialistickiPregled.Pregled();
    }

    /**
     * Create an instance of {@link IzborPromenaLekara.ProsliLekar }
     *
     */
    public IzborPromenaLekara.ProsliLekar createIzborPromenaLekaraProsliLekar() {
        return new IzborPromenaLekara.ProsliLekar();
    }

    /**
     * Create an instance of {@link IzborPromenaLekara.Lekar }
     *
     */
    public IzborPromenaLekara.Lekar createIzborPromenaLekaraLekar() {
        return new IzborPromenaLekara.Lekar();
    }

    /**
     * Create an instance of {@link IzborPromenaLekara.Pacijent }
     *
     */
    public IzborPromenaLekara.Pacijent createIzborPromenaLekaraPacijent() {
        return new IzborPromenaLekara.Pacijent();
    }

    /**
     * Create an instance of {@link IzboriPromeneLekara }
     *
     */
    public IzboriPromeneLekara createIzboriPromeneLekara() {
        return new IzboriPromeneLekara();
    }

    /**
     * Create an instance of {@link IzvestajLekara.Pacijent }
     *
     */
    public IzvestajLekara.Pacijent createIzvestajLekaraPacijent() {
        return new IzvestajLekara.Pacijent();
    }

    /**
     * Create an instance of {@link IzvestajLekara.Lekar }
     *
     */
    public IzvestajLekara.Lekar createIzvestajLekaraLekar() {
        return new IzvestajLekara.Lekar();
    }

    /**
     * Create an instance of {@link IzvestajiLekara }
     *
     */
    public IzvestajiLekara createIzvestajiLekara() {
        return new IzvestajiLekara();
    }

    /**
     * Create an instance of {@link Korisnici }
     *
     */
    public Korisnici createKorisnici() {
        return new Korisnici();
    }

    /**
     * Create an instance of {@link Korisnik }
     *
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link Lek }
     *
     */
    public Lek createLek() {
        return new Lek();
    }

    /**
     * Create an instance of {@link Lekar.Korisnik }
     *
     */
    public Lekar.Korisnik createLekarKorisnik() {
        return new Lekar.Korisnik();
    }

    /**
     * Create an instance of {@link Lekari }
     *
     */
    public Lekari createLekari() {
        return new Lekari();
    }

    /**
     * Create an instance of {@link LekarskiRecept.OsiguranoLice }
     *
     */
    public LekarskiRecept.OsiguranoLice createLekarskiReceptOsiguranoLice() {
        return new LekarskiRecept.OsiguranoLice();
    }

    /**
     * Create an instance of {@link LekarskiRecept.PropisaniLek }
     *
     */
    public LekarskiRecept.PropisaniLek createLekarskiReceptPropisaniLek() {
        return new LekarskiRecept.PropisaniLek();
    }

    /**
     * Create an instance of {@link LekarskiRecept.IzdatiLek }
     *
     */
    public LekarskiRecept.IzdatiLek createLekarskiReceptIzdatiLek() {
        return new LekarskiRecept.IzdatiLek();
    }

    /**
     * Create an instance of {@link LekarskiRecept.Lekar }
     *
     */
    public LekarskiRecept.Lekar createLekarskiReceptLekar() {
        return new LekarskiRecept.Lekar();
    }

    /**
     * Create an instance of {@link LekarskiRecepti }
     *
     */
    public LekarskiRecepti createLekarskiRecepti() {
        return new LekarskiRecepti();
    }

    /**
     * Create an instance of {@link Lekovi }
     *
     */
    public Lekovi createLekovi() {
        return new Lekovi();
    }

    /**
     * Create an instance of {@link MedicinskaSestra.Korisnik }
     *
     */
    public MedicinskaSestra.Korisnik createMedicinskaSestraKorisnik() {
        return new MedicinskaSestra.Korisnik();
    }

    /**
     * Create an instance of {@link MedicinckeSestre }
     *
     */
    public MedicinckeSestre createMedicinckeSestre() {
        return new MedicinckeSestre();
    }

    /**
     * Create an instance of {@link Pacijent.Korisnik }
     *
     */
    public Pacijent.Korisnik createPacijentKorisnik() {
        return new Pacijent.Korisnik();
    }

    /**
     * Create an instance of {@link Pacijent.ZdrastveniKarton }
     *
     */
    public Pacijent.ZdrastveniKarton createPacijentZdrastveniKarton() {
        return new Pacijent.ZdrastveniKarton();
    }

    /**
     * Create an instance of {@link Pacijenti }
     *
     */
    public Pacijenti createPacijenti() {
        return new Pacijenti();
    }

    /**
     * Create an instance of {@link Pregled.Lekar }
     *
     */
    public Pregled.Lekar createPregledLekar() {
        return new Pregled.Lekar();
    }

    /**
     * Create an instance of {@link Pregledi }
     *
     */
    public Pregledi createPregledi() {
        return new Pregledi();
    }

    /**
     * Create an instance of {@link UputZaLaboratoriju.ZdrastveneUstanove }
     *
     */
    public UputZaLaboratoriju.ZdrastveneUstanove createUputZaLaboratorijuZdrastveneUstanove() {
        return new UputZaLaboratoriju.ZdrastveneUstanove();
    }

    /**
     * Create an instance of {@link UputZaLaboratoriju.OsiguranoLice }
     *
     */
    public UputZaLaboratoriju.OsiguranoLice createUputZaLaboratorijuOsiguranoLice() {
        return new UputZaLaboratoriju.OsiguranoLice();
    }

    /**
     * Create an instance of {@link UputZaLaboratoriju.Pregled }
     *
     */
    public UputZaLaboratoriju.Pregled createUputZaLaboratorijuPregled() {
        return new UputZaLaboratoriju.Pregled();
    }

    /**
     * Create an instance of {@link UputZaLaboratoriju.Lekar }
     *
     */
    public UputZaLaboratoriju.Lekar createUputZaLaboratorijuLekar() {
        return new UputZaLaboratoriju.Lekar();
    }

    /**
     * Create an instance of {@link UputZaSpecialistickiPregled.ZdrastveneUstanove }
     *
     */
    public UputZaSpecialistickiPregled.ZdrastveneUstanove createUputZaSpecialistickiPregledZdrastveneUstanove() {
        return new UputZaSpecialistickiPregled.ZdrastveneUstanove();
    }

    /**
     * Create an instance of {@link UputZaSpecialistickiPregled.OsiguranoLice }
     *
     */
    public UputZaSpecialistickiPregled.OsiguranoLice createUputZaSpecialistickiPregledOsiguranoLice() {
        return new UputZaSpecialistickiPregled.OsiguranoLice();
    }

    /**
     * Create an instance of {@link UputiZaLaboratoriju }
     *
     */
    public UputiZaLaboratoriju createUputiZaLaboratoriju() {
        return new UputiZaLaboratoriju();
    }

    /**
     * Create an instance of {@link UputiZaSpecialistickiPregled }
     *
     */
    public UputiZaSpecialistickiPregled createUputiZaSpecialistickiPregled() {
        return new UputiZaSpecialistickiPregled();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.NosilacOsiguranja }
     *
     */
    public ZdravstveniKarton.NosilacOsiguranja createZdravstveniKartonNosilacOsiguranja() {
        return new ZdravstveniKarton.NosilacOsiguranja();
    }

    /**
     * Create an instance of {@link ZdravstveniKartoni }
     *
     */
    public ZdravstveniKartoni createZdravstveniKartoni() {
        return new ZdravstveniKartoni();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.IzmenePromeneLekara.IzmenaPromenaLekara }
     *
     */
    public ZdravstveniKarton.IzmenePromeneLekara.IzmenaPromenaLekara createZdravstveniKartonIzmenePromeneLekaraIzmenaPromenaLekara() {
        return new ZdravstveniKarton.IzmenePromeneLekara.IzmenaPromenaLekara();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.IzvestajiLekara.IzvestajLekara }
     *
     */
    public ZdravstveniKarton.IzvestajiLekara.IzvestajLekara createZdravstveniKartonIzvestajiLekaraIzvestajLekara() {
        return new ZdravstveniKarton.IzvestajiLekara.IzvestajLekara();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.LekarskiRecepti.LekraskiRecept }
     *
     */
    public ZdravstveniKarton.LekarskiRecepti.LekraskiRecept createZdravstveniKartonLekarskiReceptiLekraskiRecept() {
        return new ZdravstveniKarton.LekarskiRecepti.LekraskiRecept();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.UputiZaSpecialistickiPregled.UputZaSpecialistickiPregled }
     *
     */
    public ZdravstveniKarton.UputiZaSpecialistickiPregled.UputZaSpecialistickiPregled createZdravstveniKartonUputiZaSpecialistickiPregledUputZaSpecialistickiPregled() {
        return new ZdravstveniKarton.UputiZaSpecialistickiPregled.UputZaSpecialistickiPregled();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.UputiZaLaboratoriju.UputZaLaboratoriju }
     *
     */
    public ZdravstveniKarton.UputiZaLaboratoriju.UputZaLaboratoriju createZdravstveniKartonUputiZaLaboratorijuUputZaLaboratoriju() {
        return new ZdravstveniKarton.UputiZaLaboratoriju.UputZaLaboratoriju();
    }

    /**
     * Create an instance of {@link ZdravstveniKarton.Adresa.Opstina }
     *
     */
    public ZdravstveniKarton.Adresa.Opstina createZdravstveniKartonAdresaOpstina() {
        return new ZdravstveniKarton.Adresa.Opstina();
    }

    /**
     * Create an instance of {@link UputZaSpecialistickiPregled.IzvestajSpecialiste.Specialista }
     *
     */
    public UputZaSpecialistickiPregled.IzvestajSpecialiste.Specialista createUputZaSpecialistickiPregledIzvestajSpecialisteSpecialista() {
        return new UputZaSpecialistickiPregled.IzvestajSpecialiste.Specialista();
    }

    /**
     * Create an instance of {@link UputZaSpecialistickiPregled.Pregled.Lekar }
     *
     */
    public UputZaSpecialistickiPregled.Pregled.Lekar createUputZaSpecialistickiPregledPregledLekar() {
        return new UputZaSpecialistickiPregled.Pregled.Lekar();
    }

}
