//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.17 at 02:07:47 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://zis.rs/zis/seme/zdrastveni_kartoni", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package zis.rs.zis.domain;
