//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 10:33:15 PM CET 
//


package zis.rs.zis.domain.documents;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="naziv_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tip_obrasca"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="izbor"/&gt;
 *               &lt;enumeration value="promena"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="razlog_promene"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="ne_radi"/&gt;
 *               &lt;enumeration value="promena_prebivalista"/&gt;
 *               &lt;enumeration value="nezadovoljstvo"/&gt;
 *               &lt;enumeration value="odsutan"/&gt;
 *               &lt;enumeration value="nesporazum"/&gt;
 *               &lt;enumeration value="drugo"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ustanova_proslog_lekara" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="prosli_lekar"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/Izbor_promena_lekara}identifikator"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lekar"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/Izbor_promena_lekara}identifikator"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="pacijent"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/Izbor_promena_lekara}identifikator"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="oznaka" type="{http://www.w3.org/2001/XMLSchema}string" fixed="ipl1" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="aktivan" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "nazivUstanove",
        "tipObrasca",
        "razlogPromene",
        "ustanovaProslogLekara",
        "prosliLekar",
        "lekar",
        "pacijent",
        "datum"
})
@XmlRootElement(name = "izbor_promena_lekara")
public class IzborPromenaLekara {

    @XmlElement(name = "naziv_ustanove", required = true)
    protected String nazivUstanove;
    @XmlElement(name = "tip_obrasca", required = true, defaultValue = "izbor")
    protected String tipObrasca;
    @XmlElement(name = "razlog_promene", required = true, defaultValue = "ne_radi")
    protected String razlogPromene;
    @XmlElement(name = "ustanova_proslog_lekara", required = true)
    protected String ustanovaProslogLekara;
    @XmlElement(name = "prosli_lekar", required = true)
    protected IzborPromenaLekara.ProsliLekar prosliLekar;
    @XmlElement(required = true)
    protected IzborPromenaLekara.Lekar lekar;
    @XmlElement(required = true)
    protected IzborPromenaLekara.Pacijent pacijent;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "oznaka")
    protected String oznaka;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "aktivan", required = true)
    protected boolean aktivan;

    /**
     * Gets the value of the nazivUstanove property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNazivUstanove() {
        return nazivUstanove;
    }

    /**
     * Sets the value of the nazivUstanove property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNazivUstanove(String value) {
        this.nazivUstanove = value;
    }

    /**
     * Gets the value of the tipObrasca property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTipObrasca() {
        return tipObrasca;
    }

    /**
     * Sets the value of the tipObrasca property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTipObrasca(String value) {
        this.tipObrasca = value;
    }

    /**
     * Gets the value of the razlogPromene property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRazlogPromene() {
        return razlogPromene;
    }

    /**
     * Sets the value of the razlogPromene property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRazlogPromene(String value) {
        this.razlogPromene = value;
    }

    /**
     * Gets the value of the ustanovaProslogLekara property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUstanovaProslogLekara() {
        return ustanovaProslogLekara;
    }

    /**
     * Sets the value of the ustanovaProslogLekara property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUstanovaProslogLekara(String value) {
        this.ustanovaProslogLekara = value;
    }

    /**
     * Gets the value of the prosliLekar property.
     *
     * @return possible object is
     * {@link IzborPromenaLekara.ProsliLekar }
     */
    public IzborPromenaLekara.ProsliLekar getProsliLekar() {
        return prosliLekar;
    }

    /**
     * Sets the value of the prosliLekar property.
     *
     * @param value allowed object is
     *              {@link IzborPromenaLekara.ProsliLekar }
     */
    public void setProsliLekar(IzborPromenaLekara.ProsliLekar value) {
        this.prosliLekar = value;
    }

    /**
     * Gets the value of the lekar property.
     *
     * @return possible object is
     * {@link IzborPromenaLekara.Lekar }
     */
    public IzborPromenaLekara.Lekar getLekar() {
        return lekar;
    }

    /**
     * Sets the value of the lekar property.
     *
     * @param value allowed object is
     *              {@link IzborPromenaLekara.Lekar }
     */
    public void setLekar(IzborPromenaLekara.Lekar value) {
        this.lekar = value;
    }

    /**
     * Gets the value of the pacijent property.
     *
     * @return possible object is
     * {@link IzborPromenaLekara.Pacijent }
     */
    public IzborPromenaLekara.Pacijent getPacijent() {
        return pacijent;
    }

    /**
     * Sets the value of the pacijent property.
     *
     * @param value allowed object is
     *              {@link IzborPromenaLekara.Pacijent }
     */
    public void setPacijent(IzborPromenaLekara.Pacijent value) {
        this.pacijent = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the oznaka property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOznaka() {
        if (oznaka == null) {
            return "ipl1";
        } else {
            return oznaka;
        }
    }

    /**
     * Sets the value of the oznaka property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOznaka(String value) {
        this.oznaka = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the aktivan property.
     */
    public boolean isAktivan() {
        return aktivan;
    }

    /**
     * Sets the value of the aktivan property.
     */
    public void setAktivan(boolean value) {
        this.aktivan = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/Izbor_promena_lekara}identifikator"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Lekar {

        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/Izbor_promena_lekara")
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the identifikator property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/Izbor_promena_lekara}identifikator"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Pacijent {

        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/Izbor_promena_lekara")
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the identifikator property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/Izbor_promena_lekara}identifikator"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ProsliLekar {

        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/Izbor_promena_lekara")
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the identifikator property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }

}
