//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 10:33:15 PM CET 
//


package zis.rs.zis.domain.documents;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="naziv_zdrastvene_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="osigurano_lice"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="osnova_oslobadjenja_participacije"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;enumeration value="511"/&gt;
 *               &lt;enumeration value="512"/&gt;
 *               &lt;enumeration value="513"/&gt;
 *               &lt;enumeration value="515"/&gt;
 *               &lt;enumeration value="231"/&gt;
 *               &lt;enumeration value="232"/&gt;
 *               &lt;enumeration value="233"/&gt;
 *               &lt;enumeration value="234"/&gt;
 *               &lt;enumeration value="235"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="drzava" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datum_propisivanje_leka" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="datum_izdavanja_leka" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="dijagnoza"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{4}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="opis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="propisani_lek"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="izdati_lek"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="kolicina"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                         &lt;minInclusive value="0"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lekar"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="oznaka" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="lr1" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="bar_kod" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value=""/&gt;
 *             &lt;pattern value="[0-9]{7}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="aktivan" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazivZdrastveneUstanove",
    "osiguranoLice",
    "osnovaOslobadjenjaParticipacije",
    "drzava",
    "datumPropisivanjeLeka",
    "datumIzdavanjaLeka",
    "dijagnoza",
    "opis",
    "propisaniLek",
    "izdatiLek",
    "lekar"
})
@XmlRootElement(name = "lekarski_recept", namespace = "http://zis.rs/zis/seme/lekarski_recept")
public class LekarskiRecept {

    @XmlElement(name = "naziv_zdrastvene_ustanove", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected String nazivZdrastveneUstanove;
    @XmlElement(name = "osigurano_lice", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected LekarskiRecept.OsiguranoLice osiguranoLice;
    @XmlElement(name = "osnova_oslobadjenja_participacije", namespace = "http://zis.rs/zis/seme/lekarski_recept", defaultValue = "512")
    protected int osnovaOslobadjenjaParticipacije;
    @XmlElement(namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected String drzava;
    @XmlElement(name = "datum_propisivanje_leka", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPropisivanjeLeka;
    @XmlElement(name = "datum_izdavanja_leka", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanjaLeka;
    @XmlElement(namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected String dijagnoza;
    @XmlElement(namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected String opis;
    @XmlElement(name = "propisani_lek", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected LekarskiRecept.PropisaniLek propisaniLek;
    @XmlElement(name = "izdati_lek", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected LekarskiRecept.IzdatiLek izdatiLek;
    @XmlElement(namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
    protected LekarskiRecept.Lekar lekar;
    @XmlAttribute(name = "oznaka", required = true)
    protected String oznaka;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "bar_kod", required = true)
    protected String barKod;
    @XmlAttribute(name = "aktivan", required = true)
    protected boolean aktivan;

    /**
     * Gets the value of the nazivZdrastveneUstanove property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNazivZdrastveneUstanove() {
        return nazivZdrastveneUstanove;
    }

    /**
     * Sets the value of the nazivZdrastveneUstanove property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNazivZdrastveneUstanove(String value) {
        this.nazivZdrastveneUstanove = value;
    }

    /**
     * Gets the value of the osiguranoLice property.
     *
     * @return
     *     possible object is
     *     {@link LekarskiRecept.OsiguranoLice }
     *
     */
    public LekarskiRecept.OsiguranoLice getOsiguranoLice() {
        return osiguranoLice;
    }

    /**
     * Sets the value of the osiguranoLice property.
     *
     * @param value
     *     allowed object is
     *     {@link LekarskiRecept.OsiguranoLice }
     *
     */
    public void setOsiguranoLice(LekarskiRecept.OsiguranoLice value) {
        this.osiguranoLice = value;
    }

    /**
     * Gets the value of the osnovaOslobadjenjaParticipacije property.
     *
     */
    public int getOsnovaOslobadjenjaParticipacije() {
        return osnovaOslobadjenjaParticipacije;
    }

    /**
     * Sets the value of the osnovaOslobadjenjaParticipacije property.
     *
     */
    public void setOsnovaOslobadjenjaParticipacije(int value) {
        this.osnovaOslobadjenjaParticipacije = value;
    }

    /**
     * Gets the value of the drzava property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDrzava() {
        return drzava;
    }

    /**
     * Sets the value of the drzava property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDrzava(String value) {
        this.drzava = value;
    }

    /**
     * Gets the value of the datumPropisivanjeLeka property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatumPropisivanjeLeka() {
        return datumPropisivanjeLeka;
    }

    /**
     * Sets the value of the datumPropisivanjeLeka property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatumPropisivanjeLeka(XMLGregorianCalendar value) {
        this.datumPropisivanjeLeka = value;
    }

    /**
     * Gets the value of the datumIzdavanjaLeka property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatumIzdavanjaLeka() {
        return datumIzdavanjaLeka;
    }

    /**
     * Sets the value of the datumIzdavanjaLeka property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatumIzdavanjaLeka(XMLGregorianCalendar value) {
        this.datumIzdavanjaLeka = value;
    }

    /**
     * Gets the value of the dijagnoza property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDijagnoza() {
        return dijagnoza;
    }

    /**
     * Sets the value of the dijagnoza property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDijagnoza(String value) {
        this.dijagnoza = value;
    }

    /**
     * Gets the value of the opis property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOpis(String value) {
        this.opis = value;
    }

    /**
     * Gets the value of the propisaniLek property.
     *
     * @return
     *     possible object is
     *     {@link LekarskiRecept.PropisaniLek }
     *
     */
    public LekarskiRecept.PropisaniLek getPropisaniLek() {
        return propisaniLek;
    }

    /**
     * Sets the value of the propisaniLek property.
     *
     * @param value
     *     allowed object is
     *     {@link LekarskiRecept.PropisaniLek }
     *
     */
    public void setPropisaniLek(LekarskiRecept.PropisaniLek value) {
        this.propisaniLek = value;
    }

    /**
     * Gets the value of the izdatiLek property.
     *
     * @return
     *     possible object is
     *     {@link LekarskiRecept.IzdatiLek }
     *
     */
    public LekarskiRecept.IzdatiLek getIzdatiLek() {
        return izdatiLek;
    }

    /**
     * Sets the value of the izdatiLek property.
     *
     * @param value
     *     allowed object is
     *     {@link LekarskiRecept.IzdatiLek }
     *
     */
    public void setIzdatiLek(LekarskiRecept.IzdatiLek value) {
        this.izdatiLek = value;
    }

    /**
     * Gets the value of the lekar property.
     *
     * @return
     *     possible object is
     *     {@link LekarskiRecept.Lekar }
     *
     */
    public LekarskiRecept.Lekar getLekar() {
        return lekar;
    }

    /**
     * Sets the value of the lekar property.
     *
     * @param value
     *     allowed object is
     *     {@link LekarskiRecept.Lekar }
     *
     */
    public void setLekar(LekarskiRecept.Lekar value) {
        this.lekar = value;
    }

    /**
     * Gets the value of the oznaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznaka() {
        if (oznaka == null) {
            return "lr1";
        } else {
            return oznaka;
        }
    }

    /**
     * Sets the value of the oznaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznaka(String value) {
        this.oznaka = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the barKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarKod() {
        return barKod;
    }

    /**
     * Sets the value of the barKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarKod(String value) {
        this.barKod = value;
    }

    /**
     * Gets the value of the aktivan property.
     * 
     */
    public boolean isAktivan() {
        return aktivan;
    }

    /**
     * Sets the value of the aktivan property.
     * 
     */
    public void setAktivan(boolean value) {
        this.aktivan = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="kolicina"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *               &lt;minInclusive value="0"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kolicina"
    })
    public static class IzdatiLek {

        @XmlElement(namespace = "http://zis.rs/zis/seme/lekarski_recept")
        protected int kolicina;
        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the kolicina property.
         * 
         */
        public int getKolicina() {
            return kolicina;
        }

        /**
         * Sets the value of the kolicina property.
         * 
         */
        public void setKolicina(int value) {
            this.kolicina = value;
        }

        /**
         * Gets the value of the identifikator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Lekar {

        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the identifikator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OsiguranoLice {

        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the identifikator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/lekarski_recept}identifikator use="required""/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PropisaniLek {

        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/lekarski_recept", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the identifikator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }

}
