//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.15 at 04:55:53 PM CET 
//


package zis.rs.zis.domain.documents;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zdrastvene_ustanove"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="posaljilac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="primalac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="osigurano_lice"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="registarski_broj"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="[0-9]"/&gt;
 *                         &lt;length value="10"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="osnova_osiguranja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/uput_za_laboratoriju}identifikator"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="pregled"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="datum_preuzimanja_materijala" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="posaljilac_materijala" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="posaljilac_pregleda" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="opis_pregleda" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="lekar"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute ref="{http://zis.rs/zis/seme/uput_za_laboratoriju}identifikator"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="oznaka" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="oz1" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "zdrastveneUstanove",
        "osiguranoLice",
        "pregled",
        "datum",
        "lekar"
})
@XmlRootElement(name = "uput_za_laboratoriju", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju")
public class UputZaLaboratoriju {

    @XmlElement(name = "zdrastvene_ustanove", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
    protected ZdrastveneUstanove zdrastveneUstanove;
    @XmlElement(name = "osigurano_lice", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
    protected OsiguranoLice osiguranoLice;
    @XmlElement(namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
    protected Pregled pregled;
    @XmlElement(namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
    protected Lekar lekar;
    @XmlAttribute(name = "oznaka", required = true)
    protected String oznaka;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the zdrastveneUstanove property.
     *
     * @return possible object is
     * {@link ZdrastveneUstanove }
     */
    public ZdrastveneUstanove getZdrastveneUstanove() {
        return zdrastveneUstanove;
    }

    /**
     * Sets the value of the zdrastveneUstanove property.
     *
     * @param value allowed object is
     *              {@link ZdrastveneUstanove }
     */
    public void setZdrastveneUstanove(ZdrastveneUstanove value) {
        this.zdrastveneUstanove = value;
    }

    /**
     * Gets the value of the osiguranoLice property.
     *
     * @return possible object is
     * {@link OsiguranoLice }
     */
    public OsiguranoLice getOsiguranoLice() {
        return osiguranoLice;
    }

    /**
     * Sets the value of the osiguranoLice property.
     *
     * @param value allowed object is
     *              {@link OsiguranoLice }
     */
    public void setOsiguranoLice(OsiguranoLice value) {
        this.osiguranoLice = value;
    }

    /**
     * Gets the value of the pregled property.
     *
     * @return possible object is
     * {@link Pregled }
     */
    public Pregled getPregled() {
        return pregled;
    }

    /**
     * Sets the value of the pregled property.
     *
     * @param value allowed object is
     *              {@link Pregled }
     */
    public void setPregled(Pregled value) {
        this.pregled = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the lekar property.
     *
     * @return possible object is
     * {@link Lekar }
     */
    public Lekar getLekar() {
        return lekar;
    }

    /**
     * Sets the value of the lekar property.
     *
     * @param value allowed object is
     *              {@link Lekar }
     */
    public void setLekar(Lekar value) {
        this.lekar = value;
    }

    /**
     * Gets the value of the oznaka property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOznaka() {
        if (oznaka == null) {
            return "oz1";
        } else {
            return oznaka;
        }
    }

    /**
     * Sets the value of the oznaka property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOznaka(String value) {
        this.oznaka = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/uput_za_laboratoriju}identifikator"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Lekar {

        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju")
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the identifikator property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="registarski_broj"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="[0-9]"/&gt;
     *               &lt;length value="10"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="osnova_osiguranja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute ref="{http://zis.rs/zis/seme/uput_za_laboratoriju}identifikator"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "registarskiBroj",
            "osnovaOsiguranja"
    })
    public static class OsiguranoLice {

        @XmlElement(name = "registarski_broj", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String registarskiBroj;
        @XmlElement(name = "osnova_osiguranja", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String osnovaOsiguranja;
        @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju")
        @XmlSchemaType(name = "anyURI")
        protected String identifikator;

        /**
         * Gets the value of the registarskiBroj property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getRegistarskiBroj() {
            return registarskiBroj;
        }

        /**
         * Sets the value of the registarskiBroj property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setRegistarskiBroj(String value) {
            this.registarskiBroj = value;
        }

        /**
         * Gets the value of the osnovaOsiguranja property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getOsnovaOsiguranja() {
            return osnovaOsiguranja;
        }

        /**
         * Sets the value of the osnovaOsiguranja property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setOsnovaOsiguranja(String value) {
            this.osnovaOsiguranja = value;
        }

        /**
         * Gets the value of the identifikator property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIdentifikator() {
            return identifikator;
        }

        /**
         * Sets the value of the identifikator property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIdentifikator(String value) {
            this.identifikator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="datum_preuzimanja_materijala" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="posaljilac_materijala" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="posaljilac_pregleda" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="opis_pregleda" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "dijagnoza",
            "datumPreuzimanjaMaterijala",
            "posaljilacMaterijala",
            "posaljilacPregleda",
            "opisPregleda"
    })
    public static class Pregled {

        @XmlElement(namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String dijagnoza;
        @XmlElement(name = "datum_preuzimanja_materijala", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String datumPreuzimanjaMaterijala;
        @XmlElement(name = "posaljilac_materijala", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String posaljilacMaterijala;
        @XmlElement(name = "posaljilac_pregleda", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String posaljilacPregleda;
        @XmlElement(name = "opis_pregleda", namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String opisPregleda;

        /**
         * Gets the value of the dijagnoza property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDijagnoza() {
            return dijagnoza;
        }

        /**
         * Sets the value of the dijagnoza property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDijagnoza(String value) {
            this.dijagnoza = value;
        }

        /**
         * Gets the value of the datumPreuzimanjaMaterijala property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDatumPreuzimanjaMaterijala() {
            return datumPreuzimanjaMaterijala;
        }

        /**
         * Sets the value of the datumPreuzimanjaMaterijala property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDatumPreuzimanjaMaterijala(String value) {
            this.datumPreuzimanjaMaterijala = value;
        }

        /**
         * Gets the value of the posaljilacMaterijala property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPosaljilacMaterijala() {
            return posaljilacMaterijala;
        }

        /**
         * Sets the value of the posaljilacMaterijala property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPosaljilacMaterijala(String value) {
            this.posaljilacMaterijala = value;
        }

        /**
         * Gets the value of the posaljilacPregleda property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPosaljilacPregleda() {
            return posaljilacPregleda;
        }

        /**
         * Sets the value of the posaljilacPregleda property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPosaljilacPregleda(String value) {
            this.posaljilacPregleda = value;
        }

        /**
         * Gets the value of the opisPregleda property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getOpisPregleda() {
            return opisPregleda;
        }

        /**
         * Sets the value of the opisPregleda property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setOpisPregleda(String value) {
            this.opisPregleda = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="posaljilac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="primalac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "posaljilac",
            "primalac"
    })
    public static class ZdrastveneUstanove {

        @XmlElement(namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String posaljilac;
        @XmlElement(namespace = "http://zis.rs/zis/seme/uput_za_laboratoriju", required = true)
        protected String primalac;

        /**
         * Gets the value of the posaljilac property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPosaljilac() {
            return posaljilac;
        }

        /**
         * Sets the value of the posaljilac property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPosaljilac(String value) {
            this.posaljilac = value;
        }

        /**
         * Gets the value of the primalac property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPrimalac() {
            return primalac;
        }

        /**
         * Sets the value of the primalac property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPrimalac(String value) {
            this.primalac = value;
        }

    }

}
