//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.15 at 04:55:53 PM CET 
//


package zis.rs.zis.domain.documents;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://zis.rs/zis/sema/zdrastveni_karton}pacijent"/&gt;
 *         &lt;group ref="{http://zis.rs/zis/sema/zdrastveni_karton}dokumenti"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="jmbg" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="[0-9]{13}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="broj_zdr_knjizice" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="[0-9]{11}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="broj_kartona" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="[a-zA-Z]{2}[0-9]{3}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="lbo" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;pattern value="[0-9]{11}"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="upozorenje" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "pol",
        "nosilacOsiguranja",
        "bracnoStanje",
        "datumRodjenja",
        "adresa",
        "brojTelefona",
        "uputiZaLaboratoriju",
        "uputiZaSpecialistickiPregled",
        "lekarskiRecepti",
        "izvestajiLekara",
        "izmenePromeneLekara"
})
@XmlRootElement(name = "zdravstveni_karton", namespace = "http://zis.rs/zis/sema/zdrastveni_karton")
public class ZdravstveniKarton {

    @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected String ime;
    @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected String prezime;
    @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected String pol;
    @XmlElement(name = "nosilac_osiguranja", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected NosilacOsiguranja nosilacOsiguranja;
    @XmlElement(name = "bracno_stanje", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected String bracnoStanje;
    @XmlElement(name = "datum_rodjenja", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRodjenja;
    @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected Adresa adresa;
    @XmlElement(name = "broj_telefona", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected String brojTelefona;
    @XmlElement(name = "uputi_za_laboratoriju", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected UputiZaLaboratoriju uputiZaLaboratoriju;
    @XmlElement(name = "uputi_za_specialisticki_pregled", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected UputiZaSpecialistickiPregled uputiZaSpecialistickiPregled;
    @XmlElement(name = "lekarski_recepti", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected LekarskiRecepti lekarskiRecepti;
    @XmlElement(name = "izvestaji_lekara", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected IzvestajiLekara izvestajiLekara;
    @XmlElement(name = "izmene_promene_lekara", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
    protected IzmenePromeneLekara izmenePromeneLekara;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "jmbg", required = true)
    protected String jmbg;
    @XmlAttribute(name = "broj_zdr_knjizice", required = true)
    protected String brojZdrKnjizice;
    @XmlAttribute(name = "broj_kartona", required = true)
    protected String brojKartona;
    @XmlAttribute(name = "lbo", required = true)
    protected String lbo;
    @XmlAttribute(name = "upozorenje")
    protected String upozorenje;

    /**
     * Gets the value of the ime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the prezime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the pol property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPol() {
        return pol;
    }

    /**
     * Sets the value of the pol property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPol(String value) {
        this.pol = value;
    }

    /**
     * Gets the value of the nosilacOsiguranja property.
     *
     * @return possible object is
     * {@link NosilacOsiguranja }
     */
    public NosilacOsiguranja getNosilacOsiguranja() {
        return nosilacOsiguranja;
    }

    /**
     * Sets the value of the nosilacOsiguranja property.
     *
     * @param value allowed object is
     *              {@link NosilacOsiguranja }
     */
    public void setNosilacOsiguranja(NosilacOsiguranja value) {
        this.nosilacOsiguranja = value;
    }

    /**
     * Gets the value of the bracnoStanje property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBracnoStanje() {
        return bracnoStanje;
    }

    /**
     * Sets the value of the bracnoStanje property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBracnoStanje(String value) {
        this.bracnoStanje = value;
    }

    /**
     * Gets the value of the datumRodjenja property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDatumRodjenja() {
        return datumRodjenja;
    }

    /**
     * Sets the value of the datumRodjenja property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDatumRodjenja(XMLGregorianCalendar value) {
        this.datumRodjenja = value;
    }

    /**
     * Gets the value of the adresa property.
     *
     * @return possible object is
     * {@link Adresa }
     */
    public Adresa getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     *
     * @param value allowed object is
     *              {@link Adresa }
     */
    public void setAdresa(Adresa value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the brojTelefona property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrojTelefona() {
        return brojTelefona;
    }

    /**
     * Sets the value of the brojTelefona property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrojTelefona(String value) {
        this.brojTelefona = value;
    }

    /**
     * Gets the value of the uputiZaLaboratoriju property.
     *
     * @return possible object is
     * {@link UputiZaLaboratoriju }
     */
    public UputiZaLaboratoriju getUputiZaLaboratoriju() {
        return uputiZaLaboratoriju;
    }

    /**
     * Sets the value of the uputiZaLaboratoriju property.
     *
     * @param value allowed object is
     *              {@link UputiZaLaboratoriju }
     */
    public void setUputiZaLaboratoriju(UputiZaLaboratoriju value) {
        this.uputiZaLaboratoriju = value;
    }

    /**
     * Gets the value of the uputiZaSpecialistickiPregled property.
     *
     * @return possible object is
     * {@link UputiZaSpecialistickiPregled }
     */
    public UputiZaSpecialistickiPregled getUputiZaSpecialistickiPregled() {
        return uputiZaSpecialistickiPregled;
    }

    /**
     * Sets the value of the uputiZaSpecialistickiPregled property.
     *
     * @param value allowed object is
     *              {@link UputiZaSpecialistickiPregled }
     */
    public void setUputiZaSpecialistickiPregled(UputiZaSpecialistickiPregled value) {
        this.uputiZaSpecialistickiPregled = value;
    }

    /**
     * Gets the value of the lekarskiRecepti property.
     *
     * @return possible object is
     * {@link LekarskiRecepti }
     */
    public LekarskiRecepti getLekarskiRecepti() {
        return lekarskiRecepti;
    }

    /**
     * Sets the value of the lekarskiRecepti property.
     *
     * @param value allowed object is
     *              {@link LekarskiRecepti }
     */
    public void setLekarskiRecepti(LekarskiRecepti value) {
        this.lekarskiRecepti = value;
    }

    /**
     * Gets the value of the izvestajiLekara property.
     *
     * @return possible object is
     * {@link IzvestajiLekara }
     */
    public IzvestajiLekara getIzvestajiLekara() {
        return izvestajiLekara;
    }

    /**
     * Sets the value of the izvestajiLekara property.
     *
     * @param value allowed object is
     *              {@link IzvestajiLekara }
     */
    public void setIzvestajiLekara(IzvestajiLekara value) {
        this.izvestajiLekara = value;
    }

    /**
     * Gets the value of the izmenePromeneLekara property.
     *
     * @return possible object is
     * {@link IzmenePromeneLekara }
     */
    public IzmenePromeneLekara getIzmenePromeneLekara() {
        return izmenePromeneLekara;
    }

    /**
     * Sets the value of the izmenePromeneLekara property.
     *
     * @param value allowed object is
     *              {@link IzmenePromeneLekara }
     */
    public void setIzmenePromeneLekara(IzmenePromeneLekara value) {
        this.izmenePromeneLekara = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the jmbg property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setJmbg(String value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the brojZdrKnjizice property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrojZdrKnjizice() {
        return brojZdrKnjizice;
    }

    /**
     * Sets the value of the brojZdrKnjizice property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrojZdrKnjizice(String value) {
        this.brojZdrKnjizice = value;
    }

    /**
     * Gets the value of the brojKartona property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrojKartona() {
        return brojKartona;
    }

    /**
     * Sets the value of the brojKartona property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrojKartona(String value) {
        this.brojKartona = value;
    }

    /**
     * Gets the value of the lbo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLbo() {
        return lbo;
    }

    /**
     * Sets the value of the lbo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLbo(String value) {
        this.lbo = value;
    }

    /**
     * Gets the value of the upozorenje property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUpozorenje() {
        return upozorenje;
    }

    /**
     * Sets the value of the upozorenje property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUpozorenje(String value) {
        this.upozorenje = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ulica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
     *         &lt;element name="broj_stana" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
     *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="opstina"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="postanski_broj"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
     *                         &lt;minInclusive value="11000"/&gt;
     *                         &lt;maxInclusive value="40000"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "ulica",
            "broj",
            "brojStana",
            "mesto",
            "opstina"
    })
    public static class Adresa {

        @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        protected String ulica;
        @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger broj;
        @XmlElement(name = "broj_stana", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger brojStana;
        @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        protected String mesto;
        @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        protected Opstina opstina;

        /**
         * Gets the value of the ulica property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getUlica() {
            return ulica;
        }

        /**
         * Sets the value of the ulica property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setUlica(String value) {
            this.ulica = value;
        }

        /**
         * Gets the value of the broj property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getBroj() {
            return broj;
        }

        /**
         * Sets the value of the broj property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setBroj(BigInteger value) {
            this.broj = value;
        }

        /**
         * Gets the value of the brojStana property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getBrojStana() {
            return brojStana;
        }

        /**
         * Sets the value of the brojStana property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setBrojStana(BigInteger value) {
            this.brojStana = value;
        }

        /**
         * Gets the value of the mesto property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMesto() {
            return mesto;
        }

        /**
         * Sets the value of the mesto property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMesto(String value) {
            this.mesto = value;
        }

        /**
         * Gets the value of the opstina property.
         *
         * @return possible object is
         * {@link Opstina }
         */
        public Opstina getOpstina() {
            return opstina;
        }

        /**
         * Sets the value of the opstina property.
         *
         * @param value allowed object is
         *              {@link Opstina }
         */
        public void setOpstina(Opstina value) {
            this.opstina = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="postanski_broj"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}long"&gt;
         *               &lt;minInclusive value="11000"/&gt;
         *               &lt;maxInclusive value="40000"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "naziv",
                "postanskiBroj"
        })
        public static class Opstina {

            @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
            protected String naziv;
            @XmlElement(name = "postanski_broj", namespace = "http://zis.rs/zis/sema/zdrastveni_karton")
            protected int postanskiBroj;

            /**
             * Gets the value of the naziv property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getNaziv() {
                return naziv;
            }

            /**
             * Sets the value of the naziv property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setNaziv(String value) {
                this.naziv = value;
            }

            /**
             * Gets the value of the postanskiBroj property.
             */
            public int getPostanskiBroj() {
                return postanskiBroj;
            }

            /**
             * Sets the value of the postanskiBroj property.
             */
            public void setPostanskiBroj(int value) {
                this.postanskiBroj = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="izmena_promena_lekara" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "izmenaPromenaLekara"
    })
    public static class IzmenePromeneLekara {

        @XmlElement(name = "izmena_promena_lekara", namespace = "http://zis.rs/zis/sema/zdrastveni_karton")
        protected List<IzmenaPromenaLekara> izmenaPromenaLekara;

        /**
         * Gets the value of the izmenaPromenaLekara property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the izmenaPromenaLekara property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIzmenaPromenaLekara().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IzmenaPromenaLekara }
         */
        public List<IzmenaPromenaLekara> getIzmenaPromenaLekara() {
            if (izmenaPromenaLekara == null) {
                izmenaPromenaLekara = new ArrayList<IzmenaPromenaLekara>();
            }
            return this.izmenaPromenaLekara;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class IzmenaPromenaLekara {

            @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String identifikator;

            /**
             * Gets the value of the identifikator property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIdentifikator() {
                return identifikator;
            }

            /**
             * Sets the value of the identifikator property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIdentifikator(String value) {
                this.identifikator = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="izvestaj_lekara" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "izvestajLekara"
    })
    public static class IzvestajiLekara {

        @XmlElement(name = "izvestaj_lekara", namespace = "http://zis.rs/zis/sema/zdrastveni_karton")
        protected List<IzvestajLekara> izvestajLekara;

        /**
         * Gets the value of the izvestajLekara property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the izvestajLekara property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIzvestajLekara().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IzvestajLekara }
         */
        public List<IzvestajLekara> getIzvestajLekara() {
            if (izvestajLekara == null) {
                izvestajLekara = new ArrayList<IzvestajLekara>();
            }
            return this.izvestajLekara;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class IzvestajLekara {

            @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String identifikator;

            /**
             * Gets the value of the identifikator property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIdentifikator() {
                return identifikator;
            }

            /**
             * Sets the value of the identifikator property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIdentifikator(String value) {
                this.identifikator = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lekraski_recept" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "lekraskiRecept"
    })
    public static class LekarskiRecepti {

        @XmlElement(name = "lekraski_recept", namespace = "http://zis.rs/zis/sema/zdrastveni_karton")
        protected List<LekraskiRecept> lekraskiRecept;

        /**
         * Gets the value of the lekraskiRecept property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lekraskiRecept property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLekraskiRecept().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LekraskiRecept }
         */
        public List<LekraskiRecept> getLekraskiRecept() {
            if (lekraskiRecept == null) {
                lekraskiRecept = new ArrayList<LekraskiRecept>();
            }
            return this.lekraskiRecept;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class LekraskiRecept {

            @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String identifikator;

            /**
             * Gets the value of the identifikator property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIdentifikator() {
                return identifikator;
            }

            /**
             * Sets the value of the identifikator property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIdentifikator(String value) {
                this.identifikator = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="srodstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="osnova_osiguranja" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "srodstvo",
            "osnovaOsiguranja"
    })
    public static class NosilacOsiguranja {

        @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        protected String ime;
        @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        protected String prezime;
        @XmlElement(namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        protected String srodstvo;
        @XmlElement(name = "osnova_osiguranja", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger osnovaOsiguranja;

        /**
         * Gets the value of the ime property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the srodstvo property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getSrodstvo() {
            return srodstvo;
        }

        /**
         * Sets the value of the srodstvo property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSrodstvo(String value) {
            this.srodstvo = value;
        }

        /**
         * Gets the value of the osnovaOsiguranja property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getOsnovaOsiguranja() {
            return osnovaOsiguranja;
        }

        /**
         * Sets the value of the osnovaOsiguranja property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setOsnovaOsiguranja(BigInteger value) {
            this.osnovaOsiguranja = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="uput_za_laboratoriju" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "uputZaLaboratoriju"
    })
    public static class UputiZaLaboratoriju {

        @XmlElement(name = "uput_za_laboratoriju", namespace = "http://zis.rs/zis/sema/zdrastveni_karton")
        protected List<UputZaLaboratoriju> uputZaLaboratoriju;

        /**
         * Gets the value of the uputZaLaboratoriju property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uputZaLaboratoriju property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUputZaLaboratoriju().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UputZaLaboratoriju }
         */
        public List<UputZaLaboratoriju> getUputZaLaboratoriju() {
            if (uputZaLaboratoriju == null) {
                uputZaLaboratoriju = new ArrayList<UputZaLaboratoriju>();
            }
            return this.uputZaLaboratoriju;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class UputZaLaboratoriju {

            @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String identifikator;

            /**
             * Gets the value of the identifikator property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIdentifikator() {
                return identifikator;
            }

            /**
             * Sets the value of the identifikator property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIdentifikator(String value) {
                this.identifikator = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="uput_za_specialisticki_pregled" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "uputZaSpecialistickiPregled"
    })
    public static class UputiZaSpecialistickiPregled {

        @XmlElement(name = "uput_za_specialisticki_pregled", namespace = "http://zis.rs/zis/sema/zdrastveni_karton")
        protected List<UputZaSpecialistickiPregled> uputZaSpecialistickiPregled;

        /**
         * Gets the value of the uputZaSpecialistickiPregled property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uputZaSpecialistickiPregled property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUputZaSpecialistickiPregled().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UputZaSpecialistickiPregled }
         */
        public List<UputZaSpecialistickiPregled> getUputZaSpecialistickiPregled() {
            if (uputZaSpecialistickiPregled == null) {
                uputZaSpecialistickiPregled = new ArrayList<UputZaSpecialistickiPregled>();
            }
            return this.uputZaSpecialistickiPregled;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute ref="{http://zis.rs/zis/sema/zdrastveni_karton}identifikator use="required""/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class UputZaSpecialistickiPregled {

            @XmlAttribute(name = "identifikator", namespace = "http://zis.rs/zis/sema/zdrastveni_karton", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String identifikator;

            /**
             * Gets the value of the identifikator property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIdentifikator() {
                return identifikator;
            }

            /**
             * Sets the value of the identifikator property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIdentifikator(String value) {
                this.identifikator = value;
            }

        }

    }

}
