//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 11:01:15 PM CET 
//


package zis.rs.zis.domain.documents.collections;


import zis.rs.zis.domain.documents.IzvestajLekara;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://zis.rs/zis/seme/izvestaj_lekara}izvestaj_lekara" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "izvestajLekara"
})
@XmlRootElement(name = "izvestaji_lekara", namespace = "http://zis.rs/zis/seme/izvestaji_lekara")
public class IzvestajiLekara {

    @XmlElement(name = "izvestaj_lekara", namespace = "http://zis.rs/zis/seme/izvestaj_lekara")
    protected List<IzvestajLekara> izvestajLekara;

    /**
     * Gets the value of the izvestajLekara property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the izvestajLekara property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIzvestajLekara().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IzvestajLekara }
     */
    public List<IzvestajLekara> getIzvestajLekara() {
        if (izvestajLekara == null) {
            izvestajLekara = new ArrayList<IzvestajLekara>();
        }
        return this.izvestajLekara;
    }

}
